spring:
  datasource:
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库地址：localhost:3306/数据库名
    url: jdbc:mysql://localhost:3306/school?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    # 你的账号
    username: root
    # 你的密码
    password: root

# MyBatis-Plus 的一个小配置，方便以后在控制台看 SQL 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl